import type { ComponentCapability } from "./types";

/**
 * Ground-truth catalog of reusable components in this starter.
 * Only components marked stable or beta should be used in client projects.
 * demo-only components are listed for reference but excluded from recommendations by default.
 */
export const COMPONENT_REGISTRY: ComponentCapability[] = [
  // ── SECTIONS ────────────────────────────────────────────────────────────────
  {
    id: "hero-section",
    name: "HeroSection",
    importPath: "@/components/sections/hero-section",
    category: "section",
    domains: ["general", "academy", "saas", "portfolio", "local-business"],
    description: "Full-width hero with eyebrow label, headline, description, and CTA buttons.",
    useCases: [
      "Landing page above-the-fold section",
      "SaaS product main value proposition",
      "Portfolio introduction",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: [],
    tags: ["hero", "landing", "cta", "headline"],
    visualWeight: "heavy",
    recommendedProfiles: ["premium-saas", "minimal-dashboard", "dark-tech-api", "corporate-classic", "warm-local"],
    examples: [
      {
        label: "Basic hero",
        importStatement: 'import { HeroSection } from "@/components/sections/hero-section"',
        usage: '<HeroSection eyebrow="Nouveau" title="Titre principal" description="Description" actions={[{ label: "Commencer", href: "/signup" }]} />',
      },
    ],
  },
  {
    id: "animated-hero",
    name: "AnimatedHero",
    importPath: "@/components/sections/animated-hero",
    category: "section",
    domains: ["general", "saas", "portfolio"],
    description: "Hero section with Framer Motion entrance animations on title and description.",
    useCases: [
      "Premium landing pages where motion adds polish",
      "Portfolio hero with animated entry",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Requires framer-motion in bundle — avoid if bundle size is critical."],
    tags: ["hero", "animation", "motion", "framer"],
    visualWeight: "heavy",
    recommendedProfiles: ["premium-saas", "corporate-classic"],
  },
  {
    id: "feature-grid",
    name: "FeatureGrid",
    importPath: "@/components/sections/feature-grid",
    category: "section",
    domains: ["general", "academy", "saas", "api"],
    description: "Responsive grid of feature cards with icon, title, and description.",
    useCases: [
      "SaaS feature list",
      "API capabilities overview",
      "Product benefit breakdown",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: [],
    tags: ["features", "grid", "icons", "benefits"],
    visualWeight: "medium",
    recommendedProfiles: ["premium-saas", "dark-tech-api", "minimal-dashboard"],
  },
  {
    id: "stats-section",
    name: "StatsSection",
    importPath: "@/components/sections/stats-section",
    category: "section",
    domains: ["general", "academy", "saas", "portfolio"],
    description: "Animated counter statistics displayed as a grid or banner, triggered on scroll.",
    useCases: [
      "Social proof numbers (users, revenue, uptime)",
      "Portfolio impact metrics",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: ["Counters animate once on first scroll into view via InView."],
    tags: ["stats", "numbers", "counter", "animated"],
    visualWeight: "medium",
    recommendedProfiles: ["premium-saas", "dark-tech-api", "warm-local"],
  },
  {
    id: "pricing-section",
    name: "PricingSection",
    importPath: "@/components/sections/pricing-section",
    category: "section",
    domains: ["saas", "academy", "general"],
    description: "Pricing plans in a horizontal card layout with feature lists and highlighted plan.",
    useCases: [
      "SaaS subscription tiers",
      "Agency service packages",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: [],
    tags: ["pricing", "plans", "saas", "billing"],
    visualWeight: "heavy",
    recommendedProfiles: ["premium-saas", "minimal-dashboard"],
  },
  {
    id: "faq-section",
    name: "FAQSection",
    importPath: "@/components/sections/faq-section",
    category: "section",
    domains: ["general", "academy", "saas", "local-business"],
    description: "Accordion-based FAQ with eyebrow, title, and expandable question/answer items.",
    useCases: [
      "Product FAQ below pricing",
      "Local business common questions",
    ],
    compatibleVariables: [],
    supportedStates: ["default", "expanded"],
    maturity: "stable",
    limitations: [],
    tags: ["faq", "accordion", "questions"],
  },
  {
    id: "testimonial-section",
    name: "TestimonialSection",
    importPath: "@/components/sections/testimonial-section",
    category: "section",
    domains: ["general", "academy", "saas", "local-business"],
    description: "Grid of customer testimonial quotes with author name and optional avatar.",
    useCases: ["Social proof section", "Client reviews below pricing"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: [],
    tags: ["testimonials", "reviews", "social-proof", "quotes"],
    visualWeight: "medium",
    recommendedProfiles: ["premium-saas", "warm-local", "corporate-classic"],
  },
  {
    id: "cta-section",
    name: "CTASection",
    importPath: "@/components/sections/cta-section",
    category: "section",
    domains: ["general", "academy"],
    description: "Compact call-to-action section with title, description, and action buttons.",
    useCases: ["Page bottom conversion prompt", "Between-section upsell"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["cta", "conversion", "action"],
  },
  {
    id: "logo-cloud",
    name: "LogoCloud",
    importPath: "@/components/sections/logo-cloud",
    category: "section",
    domains: ["general", "saas"],
    description: "Horizontal band of client or partner logos with optional label.",
    useCases: ["Trusted-by logos below hero", "Partner logos in footer area"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["logos", "clients", "partners", "trust"],
  },
  {
    id: "contact-section",
    name: "ContactSection",
    importPath: "@/components/sections/contact-section",
    category: "section",
    domains: ["general", "local-business", "booking"],
    description: "Contact section with address/phone/email display and a slot for a form component.",
    useCases: ["Bottom-of-page contact block", "Service page contact area"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["formSlot must be provided separately — section does not include a form."],
    tags: ["contact", "address", "phone", "email", "form-slot"],
  },
  {
    id: "project-showcase",
    name: "ProjectShowcase",
    importPath: "@/components/sections/project-showcase",
    category: "section",
    domains: ["portfolio"],
    description: "Animated grid of project cards with image, title, description, and tags.",
    useCases: ["Portfolio project gallery", "Case study overview"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["portfolio", "projects", "gallery", "showcase"],
  },

  // ── METRICS / STATS ─────────────────────────────────────────────────────────
  {
    id: "metric-card",
    name: "MetricCard",
    importPath: "@/components/dashboard-ui/metric-card",
    category: "metric",
    domains: ["dashboard", "saas", "api"],
    description: "KPI card displaying a label, numeric value, optional trend indicator, and icon.",
    useCases: [
      "Dashboard KPI grid",
      "SaaS usage metrics",
      "API quota overview",
    ],
    compatibleVariables: ["apiPortalVariables"],
    supportedStates: ["default"],
    maturity: "production",
    limitations: [],
    tags: ["kpi", "metric", "trend", "dashboard", "card"],
    visualWeight: "light",
    recommendedProfiles: ["minimal-dashboard", "premium-saas", "dark-tech-api"],
  },
  {
    id: "activity-feed",
    name: "ActivityFeed",
    importPath: "@/components/dashboard-ui/activity-feed",
    category: "timeline",
    domains: ["dashboard"],
    description: "Vertical timeline of recent activity items with icon, label, and timestamp.",
    useCases: ["Dashboard recent activity panel", "Admin audit trail sidebar"],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["activity", "feed", "timeline", "events", "dashboard"],
  },
  {
    id: "status-badge",
    name: "StatusBadge",
    importPath: "@/components/dashboard-ui/status-badge",
    category: "badge",
    domains: ["dashboard", "ecommerce", "api"],
    description: "Color-coded badge for status strings (active, inactive, pending, error, etc.).",
    useCases: [
      "Order status in table cells",
      "API key status",
      "User account state",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Color map is limited to predefined status keys."],
    tags: ["badge", "status", "color", "label"],
  },

  // ── FILTERS ─────────────────────────────────────────────────────────────────
  {
    id: "configurable-filter-bar",
    name: "ConfigurableFilterBar",
    importPath: "@/components/component-variables/configurable-filter-bar",
    category: "filter",
    domains: ["real-estate", "auto-blog", "ecommerce", "dashboard", "academy"],
    description:
      "URL-synchronized filter bar driven by a ComponentVariable[] preset. Shows active count and an Effacer reset button.",
    useCases: [
      "Real-estate listings filter",
      "Auto blog make/model/price filter",
      "E-commerce product grid filter",
    ],
    compatibleVariables: [
      "realEstateVariables",
      "autoVariables",
      "ecommerceVariables",
      "dashboardVariables",
    ],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [
      "Requires VariableProvider ancestor.",
      "Variable serialize/deserialize functions must NOT cross the Next.js server/client boundary — import presets directly in client components.",
    ],
    tags: ["filter", "url-sync", "variables", "search", "reset"],
  },
  {
    id: "filter-bar",
    name: "FilterBar",
    importPath: "@/components/dashboard-ui/filter-bar",
    category: "filter",
    domains: ["dashboard", "general"],
    description:
      "Adapter component that renders either a legacy FilterGroup or a variable-driven bar based on props.",
    useCases: [
      "Dashboard table top filter row",
      "Simple search + dropdown filter combo",
    ],
    compatibleVariables: ["dashboardVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["filter", "search", "dropdown", "dashboard"],
  },
  {
    id: "dual-range-slider",
    name: "DualRangeSlider",
    importPath: "@/components/component-variables/renderers/dual-range-slider",
    category: "filter",
    domains: ["real-estate", "ecommerce", "dashboard"],
    description:
      "Double-thumb range slider with numeric inputs, full keyboard support, and ARIA attributes.",
    useCases: [
      "Price range filter (min/max)",
      "Area or room count range",
    ],
    compatibleVariables: ["realEstateVariables", "ecommerceVariables"],
    supportedStates: ["default", "disabled"],
    maturity: "stable",
    limitations: ["No external library — custom implementation. Thumbs may be small on mobile touch targets."],
    tags: ["slider", "range", "price", "filter", "min-max"],
  },
  {
    id: "date-range-filter",
    name: "DateRangeFilter",
    importPath: "@/components/dashboard-ui/date-range-filter",
    category: "filter",
    domains: ["dashboard", "api"],
    description: "Date range picker with from/to calendar popover for filtering by date.",
    useCases: [
      "Dashboard analytics date filter",
      "API request log date range",
    ],
    compatibleVariables: ["dashboardVariables", "apiPortalVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["date", "range", "filter", "calendar", "dashboard"],
  },

  // ── TABLES ──────────────────────────────────────────────────────────────────
  {
    id: "data-table-shell",
    name: "DataTableShell",
    importPath: "@/components/dashboard-ui/data-table-shell",
    category: "table",
    domains: ["dashboard"],
    description:
      "Wrapper around DataTable that adds an empty-state slot and consistent padding.",
    useCases: [
      "Admin entity list (users, orders, keys)",
      "Dashboard data table with empty state",
    ],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["table", "data", "empty-state", "dashboard"],
  },
  {
    id: "customer-order-table",
    name: "CustomerOrderTable",
    importPath: "@/components/ecommerce/customer-order-table",
    category: "table",
    domains: ["ecommerce"],
    description: "Styled order history table with status badge and amount columns for customers.",
    useCases: ["Customer account order history page"],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["orders", "table", "ecommerce", "history"],
  },
  {
    id: "audit-log-timeline",
    name: "AuditLogTimeline",
    importPath: "@/components/dashboard-ui/audit-log-timeline",
    category: "timeline",
    domains: ["dashboard", "api"],
    description: "Vertical timeline of audit events with icon (info/success/warning/error) and timestamp.",
    useCases: ["Admin audit trail", "API key event log"],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["audit", "log", "timeline", "events", "admin"],
  },

  // ── E-COMMERCE ──────────────────────────────────────────────────────────────
  {
    id: "product-card",
    name: "ProductCard",
    importPath: "@/components/ecommerce/product-card",
    category: "card",
    domains: ["ecommerce"],
    description: "Product card with image, name, price display, rating, and add-to-cart button in grid or list layout.",
    useCases: [
      "Product listing grid",
      "Search results product list",
    ],
    compatibleVariables: ["ecommerceVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Requires CartProvider in ancestor layout."],
    tags: ["product", "card", "ecommerce", "grid", "list"],
  },
  {
    id: "price-display",
    name: "PriceDisplay",
    importPath: "@/components/ecommerce/price-display",
    category: "badge",
    domains: ["ecommerce", "general"],
    description: "Formats a price in cents with currency symbol, optional original price, and discount percentage.",
    useCases: [
      "Price inside ProductCard",
      "Cart item price",
      "Checkout summary line items",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Prices must be in cents (integer)."],
    tags: ["price", "currency", "discount", "ecommerce"],
  },
  {
    id: "rating-stars",
    name: "RatingStars",
    importPath: "@/components/ecommerce/rating-stars",
    category: "badge",
    domains: ["ecommerce", "auto-blog"],
    description: "Star rating display with half-star support and optional review count.",
    useCases: [
      "Product rating in card or detail page",
      "Vehicle review rating in auto blog",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["rating", "stars", "review", "score"],
  },
  {
    id: "cart-drawer",
    name: "CartDrawer",
    importPath: "@/components/ecommerce/cart-drawer",
    category: "drawer",
    domains: ["ecommerce"],
    description: "Slide-in cart panel with item list, quantity steppers, subtotal, and checkout CTA.",
    useCases: ["Persistent cart sidebar in e-commerce layout"],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: ["Requires CartProvider in ancestor layout. Reads from useCart() hook."],
    tags: ["cart", "drawer", "ecommerce", "sidebar"],
  },
  {
    id: "order-status-timeline",
    name: "OrderStatusTimeline",
    importPath: "@/components/ecommerce/order-status-timeline",
    category: "timeline",
    domains: ["ecommerce"],
    description: "Step-by-step order fulfillment timeline with current step highlighted.",
    useCases: ["Order detail page status tracker", "Post-purchase status page"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["order", "status", "timeline", "fulfillment", "ecommerce"],
  },
  {
    id: "checkout-steps",
    name: "CheckoutSteps",
    importPath: "@/components/ecommerce/checkout-steps",
    category: "navigation",
    domains: ["ecommerce"],
    description: "Horizontal stepper showing cart / shipping / payment / confirmation steps.",
    useCases: ["Checkout flow progress indicator"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["checkout", "stepper", "steps", "ecommerce"],
  },

  // ── BOOKING ─────────────────────────────────────────────────────────────────
  {
    id: "booking-form",
    name: "BookingForm",
    importPath: "@/components/booking/booking-form",
    category: "form",
    domains: ["booking", "local-business"],
    description: "Multi-field booking form with service, staff, date, timeslot, and customer info.",
    useCases: [
      "Appointment booking page",
      "Service reservation form",
    ],
    compatibleVariables: [],
    supportedStates: ["default", "loading", "error"],
    maturity: "stable",
    limitations: ["Requires a server action prop `action` for form submission."],
    tags: ["booking", "form", "appointment", "reservation"],
  },
  {
    id: "service-picker",
    name: "ServicePicker",
    importPath: "@/components/booking/service-picker",
    category: "form",
    domains: ["booking", "local-business"],
    description: "Radio group for selecting a service with name, duration, and price.",
    useCases: ["Step 1 of booking flow — choose service"],
    compatibleVariables: [],
    supportedStates: ["default", "selected"],
    maturity: "stable",
    limitations: [],
    tags: ["service", "picker", "booking", "radio"],
  },
  {
    id: "time-slot-grid",
    name: "TimeSlotGrid",
    importPath: "@/components/booking/time-slot-grid",
    category: "form",
    domains: ["booking", "local-business"],
    description: "Grid of available time slots as radio buttons with unavailable slots greyed out.",
    useCases: ["Time selection step in booking flow"],
    compatibleVariables: [],
    supportedStates: ["default", "selected", "disabled", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["timeslot", "grid", "booking", "time", "schedule"],
  },
  {
    id: "booking-summary-card",
    name: "BookingSummaryCard",
    importPath: "@/components/booking/booking-summary-card",
    category: "card",
    domains: ["booking", "local-business"],
    description: "Read-only summary card showing service, staff, date, and time before confirmation.",
    useCases: ["Booking review step", "Confirmation page recap"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["booking", "summary", "confirmation", "card"],
  },

  // ── API PORTAL ──────────────────────────────────────────────────────────────
  {
    id: "endpoint-row",
    name: "EndpointRow",
    importPath: "@/components/api-portal/endpoint-row",
    category: "card",
    domains: ["api"],
    description: "Single API endpoint row with HTTP method badge, path, description, and optional auth scope.",
    useCases: ["API reference endpoint list"],
    compatibleVariables: ["apiPortalVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["api", "endpoint", "http", "method", "reference"],
  },
  {
    id: "code-tabs-block",
    name: "CodeTabsBlock",
    importPath: "@/components/api-portal/code-tabs-block",
    category: "media",
    domains: ["api", "general"],
    description: "Tabbed code block with syntax highlighting across multiple languages (curl, JS, Python, etc.).",
    useCases: [
      "API documentation code samples",
      "Multi-language integration guide",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["code", "tabs", "syntax", "api", "documentation"],
  },
  {
    id: "api-key-display",
    name: "ApiKeyDisplay",
    importPath: "@/components/api-portal/api-key-display",
    category: "badge",
    domains: ["api"],
    description: "Masked API key display with copy-to-clipboard and optional reveal toggle.",
    useCases: ["API key settings page", "Developer dashboard key list"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["api-key", "masked", "copy", "security"],
  },
  {
    id: "http-method-badge",
    name: "HttpMethodBadge",
    importPath: "@/components/api-portal/http-method-badge",
    category: "badge",
    domains: ["api"],
    description: "Color-coded badge for HTTP methods (GET=green, POST=blue, PUT=orange, DELETE=red).",
    useCases: ["API reference endpoint list", "Request log viewer"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["http", "method", "badge", "rest", "api"],
  },
  {
    id: "api-usage-chart",
    name: "ApiUsageChart",
    importPath: "@/components/api-portal/api-usage-chart",
    category: "chart",
    domains: ["api", "dashboard"],
    description: "Line or bar chart of API request volume over time.",
    useCases: ["API usage analytics panel", "Developer dashboard graph"],
    compatibleVariables: ["apiPortalVariables"],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["chart", "api", "usage", "analytics", "graph"],
  },

  // ── DASHBOARD SHELL ─────────────────────────────────────────────────────────
  {
    id: "dashboard-shell",
    name: "DashboardShell",
    importPath: "@/components/dashboard-ui/dashboard-shell",
    category: "layout",
    domains: ["dashboard"],
    description: "Full-page layout wrapper with optional sidebar slot and main content area.",
    useCases: ["Admin dashboard root layout", "SaaS app dashboard wrapper"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["dashboard", "layout", "sidebar", "shell"],
  },
  {
    id: "bulk-action-bar",
    name: "BulkActionBar",
    importPath: "@/components/dashboard-ui/bulk-action-bar",
    category: "navigation",
    domains: ["dashboard"],
    description: "Fixed bottom bar that appears when table rows are selected, with action buttons and selection count.",
    useCases: ["Bulk delete / export in admin tables"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["bulk", "action", "bar", "selection", "table", "dashboard"],
  },
  {
    id: "entity-drawer",
    name: "EntityDrawer",
    importPath: "@/components/dashboard-ui/entity-drawer",
    category: "drawer",
    domains: ["dashboard"],
    description: "Side drawer for viewing or editing an entity, with title, description slot, and footer actions.",
    useCases: ["Edit user drawer", "Order detail side panel"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["drawer", "entity", "edit", "panel", "dashboard"],
  },
  {
    id: "confirm-dialog",
    name: "ConfirmDialog",
    importPath: "@/components/dashboard-ui/confirm-dialog",
    category: "dialog",
    domains: ["dashboard", "general"],
    description: "Modal confirmation dialog with title, body, confirm/cancel buttons, and optional destructive styling.",
    useCases: ["Delete confirmation modal", "Irreversible action gate"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["dialog", "confirm", "modal", "destructive", "warning"],
  },

  // ── REAL ESTATE ─────────────────────────────────────────────────────────────
  {
    id: "property-card",
    name: "PropertyCard",
    importPath: "@/components/real-estate/property-card",
    category: "card",
    domains: ["real-estate"],
    description: "Real estate listing card with image, price, address, and bedroom/bathroom/area specs.",
    useCases: ["Property listing grid", "Map sidebar listing"],
    compatibleVariables: ["realEstateVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["property", "card", "real-estate", "listing"],
  },
  {
    id: "agent-profile-card",
    name: "AgentProfileCard",
    importPath: "@/components/real-estate/agent-profile-card",
    category: "card",
    domains: ["real-estate"],
    description: "Real estate agent card with photo, name, specialty, contact info, and listing count.",
    useCases: ["Agent directory", "Property detail page agent widget"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["agent", "card", "real-estate", "contact"],
  },

  // ── AUTO BLOG ────────────────────────────────────────────────────────────────
  {
    id: "article-card",
    name: "ArticleCard",
    importPath: "@/components/auto-blog/article-card",
    category: "card",
    domains: ["auto-blog", "general"],
    description: "Blog article card with image, category tag, title, excerpt, and read-time.",
    useCases: [
      "Auto blog article listing grid",
      "General blog post list",
    ],
    compatibleVariables: ["autoVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["article", "blog", "card", "post", "auto"],
  },
  {
    id: "featured-article-card",
    name: "FeaturedArticleCard",
    importPath: "@/components/auto-blog/featured-article-card",
    category: "card",
    domains: ["auto-blog"],
    description: "Large hero-style article card for the featured/pinned post at the top of a blog.",
    useCases: ["Auto blog featured post", "Latest review spotlight"],
    compatibleVariables: ["autoVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["article", "featured", "blog", "hero", "auto"],
  },

  // ── PORTFOLIO ────────────────────────────────────────────────────────────────
  {
    id: "case-study-card",
    name: "CaseStudyCard",
    importPath: "@/components/portfolio/case-study-card",
    category: "card",
    domains: ["portfolio"],
    description: "Portfolio case study card with project image, title, client, tags, and outcome metric.",
    useCases: ["Portfolio case study grid", "Work section showcase"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["case-study", "portfolio", "project", "card", "work"],
  },
];
