import type { ComponentCapability } from "./types";

/**
 * Ground-truth catalog of reusable components in this starter.
 * Only components marked stable or beta should be used in client projects.
 * demo-only components are listed for reference but excluded from recommendations by default.
 */
export const COMPONENT_REGISTRY: ComponentCapability[] = [
  // ── SECTIONS ────────────────────────────────────────────────────────────────
  {
    id: "hero-section",
    name: "HeroSection",
    importPath: "@/components/sections/hero-section",
    category: "section",
    domains: ["general", "academy", "saas", "portfolio", "local-business"],
    description: "Full-width hero with eyebrow label, headline, description, and CTA buttons.",
    useCases: [
      "Landing page above-the-fold section",
      "SaaS product main value proposition",
      "Portfolio introduction",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: [],
    tags: ["hero", "landing", "cta", "headline"],
    visualWeight: "heavy",
    recommendedProfiles: ["premium-saas", "minimal-dashboard", "dark-technical", "creative-portfolio", "warm-local"],
    qualityLevels: ["premium", "conversion"],
    frontendPatterns: ["hero-trust-bar", "hero-proof-cta"],
    requiredStates: ["default"],
    uxNotes: [
      "h1 heading is required — one per page",
      "Primary CTA must be above the fold on 1024px",
      "Use trustBar prop to add a LogoCloud or stat row below actions",
      "Use size prop (compact/default/large) to control vertical density",
    ],
    examples: [
      {
        label: "Basic hero",
        importStatement: 'import { HeroSection } from "@/components/sections/hero-section"',
        usage: '<HeroSection eyebrow="Nouveau" title="Titre principal" description="Description" actions={[{ label: "Commencer", href: "/signup" }]} />',
      },
    ],
  },
  {
    id: "animated-hero",
    name: "AnimatedHero",
    importPath: "@/components/sections/animated-hero",
    category: "section",
    domains: ["general", "saas", "portfolio"],
    description: "Hero section with Framer Motion entrance animations on title and description.",
    useCases: [
      "Premium landing pages where motion adds polish",
      "Portfolio hero with animated entry",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Requires framer-motion in bundle — avoid if bundle size is critical."],
    tags: ["hero", "animation", "motion", "framer"],
    visualWeight: "heavy",
    recommendedProfiles: ["premium-saas", "creative-portfolio"],
  },
  {
    id: "feature-grid",
    name: "FeatureGrid",
    importPath: "@/components/sections/feature-grid",
    category: "section",
    domains: ["general", "academy", "saas", "api"],
    description: "Responsive grid of feature cards with icon, title, and description. Supports cards, icon-left, list, and spotlight variants. cardVariant prop controls the Card variant.",
    useCases: [
      "SaaS feature list",
      "API capabilities overview",
      "Product benefit breakdown",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: [],
    tags: ["features", "grid", "icons", "benefits"],
    visualWeight: "medium",
    recommendedProfiles: ["premium-saas", "dark-technical", "minimal-dashboard"],
    qualityLevels: ["polished", "premium"],
    frontendPatterns: ["feature-bento-metrics"],
    requiredStates: ["default"],
    uxNotes: [
      "Icons must have aria-hidden — they are decorative",
      "Keep 3-6 features to avoid cognitive overload",
    ],
  },
  {
    id: "stats-section",
    name: "StatsSection",
    importPath: "@/components/sections/stats-section",
    category: "section",
    domains: ["general", "academy", "saas", "portfolio"],
    description: "Animated counter statistics displayed as a grid or banner, triggered on scroll.",
    useCases: [
      "Social proof numbers (users, revenue, uptime)",
      "Portfolio impact metrics",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: ["Counters animate once on first scroll into view via InView."],
    tags: ["stats", "numbers", "counter", "animated"],
    visualWeight: "medium",
    recommendedProfiles: ["premium-saas", "dark-technical", "warm-local"],
    qualityLevels: ["premium", "conversion"],
    frontendPatterns: ["hero-proof-cta", "feature-bento-metrics"],
    requiredStates: ["default"],
    uxNotes: [
      "Counter values must be readable without animation (SSR fallback)",
      "Animate once on scroll into view — do not loop",
    ],
  },
  {
    id: "pricing-section",
    name: "PricingSection",
    importPath: "@/components/sections/pricing-section",
    category: "section",
    domains: ["saas", "academy", "general"],
    description: "Pricing plans in a horizontal card layout with feature lists and highlighted plan. Featured plan is visually elevated (shadow-lg, ring-1 primary, -my-4 vertical offset) and labeled for screen readers.",
    useCases: [
      "SaaS subscription tiers",
      "Agency service packages",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: [],
    tags: ["pricing", "plans", "saas", "billing"],
    visualWeight: "heavy",
    recommendedProfiles: ["premium-saas", "minimal-dashboard"],
    uxNotes: [
      "Set featured=true on the recommended plan — it renders visually elevated",
      "Badge prop ('Populaire', 'Recommande') appears top-right of the plan card",
      "Featured card gets aria-label='[name] — plan recommande' automatically",
    ],
  },
  {
    id: "faq-section",
    name: "FAQSection",
    importPath: "@/components/sections/faq-section",
    category: "section",
    domains: ["general", "academy", "saas", "local-business"],
    description: "Accordion-based FAQ with eyebrow, title, and expandable question/answer items.",
    useCases: [
      "Product FAQ below pricing",
      "Local business common questions",
    ],
    compatibleVariables: [],
    supportedStates: ["default", "expanded"],
    maturity: "stable",
    limitations: [],
    tags: ["faq", "accordion", "questions"],
  },
  {
    id: "testimonial-section",
    name: "TestimonialSection",
    importPath: "@/components/sections/testimonial-section",
    category: "section",
    domains: ["general", "academy", "saas", "local-business"],
    description: "Grid of customer testimonial quotes with author name and optional avatar.",
    useCases: ["Social proof section", "Client reviews below pricing"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: [],
    tags: ["testimonials", "reviews", "social-proof", "quotes"],
    visualWeight: "medium",
    recommendedProfiles: ["premium-saas", "warm-local", "luxury-editorial"],
  },
  {
    id: "cta-section",
    name: "CTASection",
    importPath: "@/components/sections/cta-section",
    category: "section",
    domains: ["general", "academy"],
    description: "Call-to-action section with optional eyebrow, title, description, and action buttons. Variants: default, dark, muted, border, gradient.",
    useCases: ["Page bottom conversion prompt", "Between-section upsell"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["cta", "conversion", "action"],
    qualityLevels: ["conversion", "polished"],
    frontendPatterns: ["pricing-faq-guarantee", "lead-capture-contact-card"],
    requiredStates: ["default"],
    uxNotes: [
      "Provide a single primary action — avoid two competing CTAs",
      "Use at page bottom as conversion closer or between sections as upsell",
    ],
  },
  {
    id: "logo-cloud",
    name: "LogoCloud",
    importPath: "@/components/sections/logo-cloud",
    category: "section",
    domains: ["general", "saas"],
    description: "Horizontal band of client or partner logos with optional label. Uses role=list with aria-label per item and aria-hidden on decorative SVGs.",
    useCases: ["Trusted-by logos below hero", "Partner logos in footer area"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["logos", "clients", "partners", "trust"],
    uxNotes: [
      "logos[].name is used as aria-label on each list item — make it the brand name",
      "logos[].logo SVG should be aria-hidden (handled by the component)",
    ],
  },
  {
    id: "contact-section",
    name: "ContactSection",
    importPath: "@/components/sections/contact-section",
    category: "section",
    domains: ["general", "local-business", "booking"],
    description: "Contact section with address/phone/email display and a slot for a form component.",
    useCases: ["Bottom-of-page contact block", "Service page contact area"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["formSlot must be provided separately — section does not include a form."],
    tags: ["contact", "address", "phone", "email", "form-slot"],
  },
  {
    id: "project-showcase",
    name: "ProjectShowcase",
    importPath: "@/components/sections/project-showcase",
    category: "section",
    domains: ["portfolio"],
    description: "Animated grid of project cards with image, title, description, and tags.",
    useCases: ["Portfolio project gallery", "Case study overview"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["portfolio", "projects", "gallery", "showcase"],
  },

  // ── METRICS / STATS ─────────────────────────────────────────────────────────
  {
    id: "metric-card",
    name: "MetricCard",
    importPath: "@/components/dashboard-ui/metric-card",
    category: "metric",
    domains: ["dashboard", "saas", "api"],
    description: "KPI card displaying a label, numeric value, optional trend indicator, and icon. Supports loading prop for skeleton state.",
    useCases: [
      "Dashboard KPI grid",
      "SaaS usage metrics",
      "API quota overview",
    ],
    compatibleVariables: ["apiPortalVariables"],
    supportedStates: ["default", "loading"],
    maturity: "production",
    limitations: [],
    tags: ["kpi", "metric", "trend", "dashboard", "card", "skeleton"],
    visualWeight: "light",
    recommendedProfiles: ["minimal-dashboard", "premium-saas", "dark-technical"],
    qualityLevels: ["dashboard", "premium"],
    frontendPatterns: ["dashboard-metrics-activity"],
    requiredStates: ["default"],
    uxNotes: [
      "Group in a 2-4 column grid for a KPI overview",
      "Trend indicator direction must match data direction — verify sign convention",
    ],
  },
  {
    id: "activity-feed",
    name: "ActivityFeed",
    importPath: "@/components/dashboard-ui/activity-feed",
    category: "timeline",
    domains: ["dashboard"],
    description: "Vertical timeline of recent activity items with icon, label, and timestamp.",
    useCases: ["Dashboard recent activity panel", "Admin audit trail sidebar"],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["activity", "feed", "timeline", "events", "dashboard"],
    qualityLevels: ["dashboard"],
    frontendPatterns: ["dashboard-metrics-activity"],
    requiredStates: ["default", "empty"],
    uxNotes: [
      "Always render ol even when empty — put the empty message in an li",
      "Empty text must be informative, not just blank",
    ],
  },
  {
    id: "status-badge",
    name: "StatusBadge",
    importPath: "@/components/dashboard-ui/status-badge",
    category: "badge",
    domains: ["dashboard", "ecommerce", "api"],
    description: "Color-coded badge for status strings (active, inactive, pending, error, etc.).",
    useCases: [
      "Order status in table cells",
      "API key status",
      "User account state",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Color map is limited to predefined status keys."],
    tags: ["badge", "status", "color", "label"],
  },

  // ── FILTERS ─────────────────────────────────────────────────────────────────
  {
    id: "configurable-filter-bar",
    name: "ConfigurableFilterBar",
    importPath: "@/components/component-variables/configurable-filter-bar",
    category: "filter",
    domains: ["real-estate", "auto-blog", "ecommerce", "dashboard", "academy"],
    description:
      "URL-synchronized filter bar driven by a ComponentVariable[] preset. Shows active count and an Effacer reset button.",
    useCases: [
      "Real-estate listings filter",
      "Auto blog make/model/price filter",
      "E-commerce product grid filter",
    ],
    compatibleVariables: [
      "realEstateVariables",
      "autoVariables",
      "ecommerceVariables",
      "dashboardVariables",
    ],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [
      "Requires VariableProvider ancestor.",
      "Variable serialize/deserialize functions must NOT cross the Next.js server/client boundary — import presets directly in client components.",
    ],
    tags: ["filter", "url-sync", "variables", "search", "reset"],
    qualityLevels: ["dashboard", "technical"],
    frontendPatterns: ["product-grid-filter-drawer", "real-estate-search-results"],
    requiredStates: ["default", "empty"],
    uxNotes: [
      "Requires VariableProvider ancestor — never render without it",
      "URL sync means filters survive page reload — test back/forward navigation",
    ],
  },
  {
    id: "filter-bar",
    name: "FilterBar",
    importPath: "@/components/dashboard-ui/filter-bar",
    category: "filter",
    domains: ["dashboard", "general"],
    description:
      "Adapter component that renders either a legacy FilterGroup or a variable-driven bar based on props.",
    useCases: [
      "Dashboard table top filter row",
      "Simple search + dropdown filter combo",
    ],
    compatibleVariables: ["dashboardVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["filter", "search", "dropdown", "dashboard"],
  },
  {
    id: "dual-range-slider",
    name: "DualRangeSlider",
    importPath: "@/components/component-variables/renderers/dual-range-slider",
    category: "filter",
    domains: ["real-estate", "ecommerce", "dashboard"],
    description:
      "Double-thumb range slider with numeric inputs, full keyboard support, and ARIA attributes.",
    useCases: [
      "Price range filter (min/max)",
      "Area or room count range",
    ],
    compatibleVariables: ["realEstateVariables", "ecommerceVariables"],
    supportedStates: ["default", "disabled"],
    maturity: "stable",
    limitations: ["No external library — custom implementation. Thumbs may be small on mobile touch targets."],
    tags: ["slider", "range", "price", "filter", "min-max"],
  },
  {
    id: "date-range-filter",
    name: "DateRangeFilter",
    importPath: "@/components/dashboard-ui/date-range-filter",
    category: "filter",
    domains: ["dashboard", "api"],
    description: "Date range picker with from/to calendar popover for filtering by date.",
    useCases: [
      "Dashboard analytics date filter",
      "API request log date range",
    ],
    compatibleVariables: ["dashboardVariables", "apiPortalVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["date", "range", "filter", "calendar", "dashboard"],
  },

  // ── TABLES ──────────────────────────────────────────────────────────────────
  {
    id: "data-table-shell",
    name: "DataTableShell",
    importPath: "@/components/dashboard-ui/data-table-shell",
    category: "table",
    domains: ["dashboard"],
    description:
      "Wrapper around DataTable that adds an empty-state slot and consistent padding.",
    useCases: [
      "Admin entity list (users, orders, keys)",
      "Dashboard data table with empty state",
    ],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["table", "data", "empty-state", "dashboard"],
    qualityLevels: ["dashboard", "technical"],
    frontendPatterns: ["dashboard-metrics-activity", "api-docs-endpoint-grid"],
    requiredStates: ["default", "empty", "loading"],
    uxNotes: [
      "Always provide an empty-state slot — never show a bare empty table",
      "Use the loading prop for skeleton display during data fetch",
    ],
  },
  {
    id: "customer-order-table",
    name: "CustomerOrderTable",
    importPath: "@/components/ecommerce/customer-order-table",
    category: "table",
    domains: ["ecommerce"],
    description: "Styled order history table with status badge and amount columns for customers.",
    useCases: ["Customer account order history page"],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["orders", "table", "ecommerce", "history"],
  },
  {
    id: "audit-log-timeline",
    name: "AuditLogTimeline",
    importPath: "@/components/dashboard-ui/audit-log-timeline",
    category: "timeline",
    domains: ["dashboard", "api"],
    description: "Vertical timeline of audit events with icon (info/success/warning/error) and timestamp.",
    useCases: ["Admin audit trail", "API key event log"],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["audit", "log", "timeline", "events", "admin"],
  },

  // ── E-COMMERCE ──────────────────────────────────────────────────────────────
  {
    id: "product-card",
    name: "ProductCard",
    importPath: "@/components/ecommerce/product-card",
    category: "card",
    domains: ["ecommerce"],
    description: "Product card with image, name, price display, rating, and add-to-cart button in grid or list layout.",
    useCases: [
      "Product listing grid",
      "Search results product list",
    ],
    compatibleVariables: ["ecommerceVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Requires CartProvider in ancestor layout."],
    tags: ["product", "card", "ecommerce", "grid", "list"],
    qualityLevels: ["polished", "premium", "conversion"],
    frontendPatterns: ["product-grid-filter-drawer"],
    requiredStates: ["default"],
    uxNotes: [
      "Requires CartProvider ancestor — never render without it",
      "Image alt text must describe the product, not just say 'product'",
    ],
  },
  {
    id: "price-display",
    name: "PriceDisplay",
    importPath: "@/components/ecommerce/price-display",
    category: "badge",
    domains: ["ecommerce", "general"],
    description: "Formats a price in cents with currency symbol, optional original price, and discount percentage.",
    useCases: [
      "Price inside ProductCard",
      "Cart item price",
      "Checkout summary line items",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Prices must be in cents (integer)."],
    tags: ["price", "currency", "discount", "ecommerce"],
  },
  {
    id: "rating-stars",
    name: "RatingStars",
    importPath: "@/components/ecommerce/rating-stars",
    category: "badge",
    domains: ["ecommerce", "auto-blog"],
    description: "Star rating display with half-star support and optional review count.",
    useCases: [
      "Product rating in card or detail page",
      "Vehicle review rating in auto blog",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["rating", "stars", "review", "score"],
  },
  {
    id: "cart-drawer",
    name: "CartDrawer",
    importPath: "@/components/ecommerce/cart-drawer",
    category: "drawer",
    domains: ["ecommerce"],
    description: "Slide-in cart panel with item list, quantity steppers, subtotal, and checkout CTA.",
    useCases: ["Persistent cart sidebar in e-commerce layout"],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: ["Requires CartProvider in ancestor layout. Reads from useCart() hook."],
    tags: ["cart", "drawer", "ecommerce", "sidebar"],
  },
  {
    id: "order-status-timeline",
    name: "OrderStatusTimeline",
    importPath: "@/components/ecommerce/order-status-timeline",
    category: "timeline",
    domains: ["ecommerce"],
    description: "Step-by-step order fulfillment timeline with current step highlighted.",
    useCases: ["Order detail page status tracker", "Post-purchase status page"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["order", "status", "timeline", "fulfillment", "ecommerce"],
  },
  {
    id: "checkout-steps",
    name: "CheckoutSteps",
    importPath: "@/components/ecommerce/checkout-steps",
    category: "navigation",
    domains: ["ecommerce"],
    description: "Horizontal stepper showing cart / shipping / payment / confirmation steps.",
    useCases: ["Checkout flow progress indicator"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["checkout", "stepper", "steps", "ecommerce"],
  },

  // ── BOOKING ─────────────────────────────────────────────────────────────────
  {
    id: "booking-form",
    name: "BookingForm",
    importPath: "@/components/booking/booking-form",
    category: "form",
    domains: ["booking", "local-business"],
    description: "Multi-field booking form with inline client-side validation, error states (aria-invalid, aria-describedby, role=alert), aria-busy on submit, and helper text.",
    useCases: [
      "Appointment booking page",
      "Service reservation form",
    ],
    compatibleVariables: [],
    supportedStates: ["default", "loading", "error"],
    maturity: "stable",
    limitations: ["Requires a server action prop `action` for form submission."],
    tags: ["booking", "form", "appointment", "reservation"],
    frontendPatterns: ["error-state-recovery"],
    uxNotes: [
      "Client-side validation runs on submit — name required, email format validated",
      "Error messages use role=alert and are linked to inputs via aria-describedby",
      "Submit button sets aria-busy=true while the server action is pending",
    ],
  },
  {
    id: "service-picker",
    name: "ServicePicker",
    importPath: "@/components/booking/service-picker",
    category: "form",
    domains: ["booking", "local-business"],
    description: "Radio group for selecting a service with name, duration, and price.",
    useCases: ["Step 1 of booking flow — choose service"],
    compatibleVariables: [],
    supportedStates: ["default", "selected"],
    maturity: "stable",
    limitations: [],
    tags: ["service", "picker", "booking", "radio"],
    qualityLevels: ["polished", "conversion"],
    frontendPatterns: ["booking-flow-confirmation"],
    requiredStates: ["default", "selected"],
    uxNotes: [
      "Keep options under 8 — more than that warrants a search or filter",
      "Radio group must have visible labels accessible to screen readers",
    ],
  },
  {
    id: "time-slot-grid",
    name: "TimeSlotGrid",
    importPath: "@/components/booking/time-slot-grid",
    category: "form",
    domains: ["booking", "local-business"],
    description: "Grid of available time slots as radio buttons with unavailable slots greyed out.",
    useCases: ["Time selection step in booking flow"],
    compatibleVariables: [],
    supportedStates: ["default", "selected", "disabled", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["timeslot", "grid", "booking", "time", "schedule"],
  },
  {
    id: "booking-summary-card",
    name: "BookingSummaryCard",
    importPath: "@/components/booking/booking-summary-card",
    category: "card",
    domains: ["booking", "local-business"],
    description: "Read-only summary card showing service, staff, date, and time before confirmation.",
    useCases: ["Booking review step", "Confirmation page recap"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["booking", "summary", "confirmation", "card"],
    qualityLevels: ["polished", "premium"],
    frontendPatterns: ["booking-flow-confirmation"],
    requiredStates: ["default"],
    uxNotes: [
      "Read-only — contains no form elements",
      "Must display all confirmed details (service, staff, date, time) before submission",
    ],
  },

  // ── API PORTAL ──────────────────────────────────────────────────────────────
  {
    id: "endpoint-row",
    name: "EndpointRow",
    importPath: "@/components/api-portal/endpoint-row",
    category: "card",
    domains: ["api"],
    description: "Single API endpoint row with HTTP method badge, path, description, and optional auth scope.",
    useCases: ["API reference endpoint list"],
    compatibleVariables: ["apiPortalVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["api", "endpoint", "http", "method", "reference"],
  },
  {
    id: "code-tabs-block",
    name: "CodeTabsBlock",
    importPath: "@/components/api-portal/code-tabs-block",
    category: "media",
    domains: ["api", "general"],
    description: "Tabbed code block with syntax highlighting across multiple languages (curl, JS, Python, etc.).",
    useCases: [
      "API documentation code samples",
      "Multi-language integration guide",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["code", "tabs", "syntax", "api", "documentation"],
  },
  {
    id: "api-key-display",
    name: "ApiKeyDisplay",
    importPath: "@/components/api-portal/api-key-display",
    category: "badge",
    domains: ["api"],
    description: "Masked API key display with copy-to-clipboard and optional reveal toggle.",
    useCases: ["API key settings page", "Developer dashboard key list"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["api-key", "masked", "copy", "security"],
  },
  {
    id: "http-method-badge",
    name: "HttpMethodBadge",
    importPath: "@/components/api-portal/http-method-badge",
    category: "badge",
    domains: ["api"],
    description: "Color-coded badge for HTTP methods (GET=green, POST=blue, PUT=orange, DELETE=red).",
    useCases: ["API reference endpoint list", "Request log viewer"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["http", "method", "badge", "rest", "api"],
  },
  {
    id: "api-usage-chart",
    name: "ApiUsageChart",
    importPath: "@/components/api-portal/api-usage-chart",
    category: "chart",
    domains: ["api", "dashboard"],
    description: "Line or bar chart of API request volume over time.",
    useCases: ["API usage analytics panel", "Developer dashboard graph"],
    compatibleVariables: ["apiPortalVariables"],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["chart", "api", "usage", "analytics", "graph"],
  },

  // ── DASHBOARD SHELL ─────────────────────────────────────────────────────────
  {
    id: "dashboard-shell",
    name: "DashboardShell",
    importPath: "@/components/dashboard-ui/dashboard-shell",
    category: "layout",
    domains: ["dashboard"],
    description: "Full-page layout wrapper with optional sidebar slot and main content area.",
    useCases: ["Admin dashboard root layout", "SaaS app dashboard wrapper"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["dashboard", "layout", "sidebar", "shell"],
    qualityLevels: ["dashboard", "technical"],
    frontendPatterns: ["dashboard-metrics-activity"],
    requiredStates: ["default"],
    uxNotes: [
      "Sidebar prop is optional — omit for full-width layouts",
      "DashboardMobileTrigger must be in the header for mobile sidebar access",
    ],
  },
  {
    id: "bulk-action-bar",
    name: "BulkActionBar",
    importPath: "@/components/dashboard-ui/bulk-action-bar",
    category: "navigation",
    domains: ["dashboard"],
    description: "Fixed bottom bar that appears when table rows are selected, with action buttons and selection count.",
    useCases: ["Bulk delete / export in admin tables"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["bulk", "action", "bar", "selection", "table", "dashboard"],
  },
  {
    id: "entity-drawer",
    name: "EntityDrawer",
    importPath: "@/components/dashboard-ui/entity-drawer",
    category: "drawer",
    domains: ["dashboard"],
    description: "Side drawer for viewing or editing an entity, with title, description slot, and footer actions.",
    useCases: ["Edit user drawer", "Order detail side panel"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["drawer", "entity", "edit", "panel", "dashboard"],
  },
  {
    id: "confirm-dialog",
    name: "ConfirmDialog",
    importPath: "@/components/dashboard-ui/confirm-dialog",
    category: "dialog",
    domains: ["dashboard", "general"],
    description: "Modal confirmation dialog with title, body, confirm/cancel buttons, and optional destructive styling.",
    useCases: ["Delete confirmation modal", "Irreversible action gate"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["dialog", "confirm", "modal", "destructive", "warning"],
  },

  // ── REAL ESTATE ─────────────────────────────────────────────────────────────
  {
    id: "property-card",
    name: "PropertyCard",
    importPath: "@/components/real-estate/property-card",
    category: "card",
    domains: ["real-estate"],
    description: "Real estate listing card with image, price, address, and bedroom/bathroom/area specs.",
    useCases: ["Property listing grid", "Map sidebar listing"],
    compatibleVariables: ["realEstateVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["property", "card", "real-estate", "listing"],
    qualityLevels: ["polished", "premium"],
    frontendPatterns: ["real-estate-search-results"],
    requiredStates: ["default"],
    uxNotes: [
      "Image alt must describe the property, not just say 'property photo'",
      "Beds/baths/sqft specs area must use semantic markup (not just div spans)",
    ],
  },
  {
    id: "agent-profile-card",
    name: "AgentProfileCard",
    importPath: "@/components/real-estate/agent-profile-card",
    category: "card",
    domains: ["real-estate"],
    description: "Real estate agent card with photo, name, specialty, contact info, and listing count.",
    useCases: ["Agent directory", "Property detail page agent widget"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["agent", "card", "real-estate", "contact"],
  },

  // ── AUTO BLOG ────────────────────────────────────────────────────────────────
  {
    id: "article-card",
    name: "ArticleCard",
    importPath: "@/components/auto-blog/article-card",
    category: "card",
    domains: ["auto-blog", "general"],
    description: "Blog article card with image, category tag, title, excerpt, and read-time.",
    useCases: [
      "Auto blog article listing grid",
      "General blog post list",
    ],
    compatibleVariables: ["autoVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["article", "blog", "card", "post", "auto"],
  },
  {
    id: "featured-article-card",
    name: "FeaturedArticleCard",
    importPath: "@/components/auto-blog/featured-article-card",
    category: "card",
    domains: ["auto-blog"],
    description: "Large hero-style article card for the featured/pinned post at the top of a blog.",
    useCases: ["Auto blog featured post", "Latest review spotlight"],
    compatibleVariables: ["autoVariables"],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["article", "featured", "blog", "hero", "auto"],
  },

  // ── PORTFOLIO ────────────────────────────────────────────────────────────────
  {
    id: "case-study-card",
    name: "CaseStudyCard",
    importPath: "@/components/portfolio/case-study-card",
    category: "card",
    domains: ["portfolio"],
    description: "Portfolio case study card with project image, title, client, tags, and outcome metric.",
    useCases: ["Portfolio case study grid", "Work section showcase"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["case-study", "portfolio", "project", "card", "work"],
  },

  // ── UX STATES ───────────────────────────────────────────────────────────────
  {
    id: "error-state",
    name: "ErrorState",
    importPath: "@/components/ui/error-state",
    category: "card",
    domains: ["general", "dashboard", "saas", "api"],
    description: "Standardized error state with icon, title, description, and optional retry action. role=alert.",
    useCases: [
      "API call failure display",
      "Data fetch error in dashboard panels",
      "Form submission error feedback",
    ],
    compatibleVariables: [],
    supportedStates: ["error"],
    maturity: "production",
    limitations: [],
    tags: ["error", "state", "feedback", "retry", "alert"],
    qualityLevels: ["polished", "dashboard", "technical"],
    frontendPatterns: ["error-state-recovery"],
    requiredStates: ["error"],
    uxNotes: [
      "role=alert ensures screen readers announce the error",
      "Always provide a retry action when the error is recoverable",
      "Default text is in French — override title/description for other locales",
    ],
  },
  {
    id: "success-state",
    name: "SuccessState",
    importPath: "@/components/ui/success-state",
    category: "card",
    domains: ["general", "dashboard", "booking", "ecommerce"],
    description: "Standardized success state with icon, title, description, and optional action. role=status + aria-live.",
    useCases: [
      "Form submission confirmation",
      "Booking confirmation",
      "Payment success",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "production",
    limitations: [],
    tags: ["success", "state", "confirmation", "feedback"],
    qualityLevels: ["polished", "conversion"],
    frontendPatterns: ["booking-flow-confirmation"],
    requiredStates: ["default"],
    uxNotes: [
      "role=status + aria-live=polite ensures screen readers announce success",
      "Use after form submit or booking confirm — not as a persistent status badge",
    ],
  },
  {
    id: "dialog",
    name: "Dialog",
    importPath: "@/components/ui/dialog",
    category: "dialog",
    domains: ["general", "dashboard", "saas", "booking", "ecommerce"],
    description: "Animated portal modal with focus trap, Escape close, scroll lock, focus restore to trigger, aria-modal, aria-labelledby/describedby props.",
    useCases: [
      "Confirmation dialogs",
      "Form in a modal",
      "Quick view overlays",
    ],
    compatibleVariables: [],
    supportedStates: ["default", "loading"],
    maturity: "production",
    limitations: [],
    tags: ["dialog", "modal", "overlay", "focus-trap"],
    frontendPatterns: ["focus-management"],
    uxNotes: [
      "Pass aria-labelledby={titleId} for screen reader dialog name",
      "Pass aria-describedby={descId} for screen reader dialog description",
      "Focus trap cycles Tab within the dialog and restores focus on close",
      "Backdrop click closes; Escape closes",
    ],
  },
  {
    id: "sheet-root",
    name: "SheetRoot",
    importPath: "@/components/ui/sheet",
    category: "drawer",
    domains: ["general", "dashboard", "saas"],
    description: "Animated slide-in panel modal (right/left/top/bottom) with focus trap, Escape close, scroll lock, focus restore. role=dialog + aria-modal.",
    useCases: [
      "Side panel with details",
      "Filter/settings panel",
      "Mobile navigation drawer",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["sheet", "drawer", "panel", "slide", "focus-trap"],
    frontendPatterns: ["focus-management"],
    uxNotes: [
      "Use side='right' (default) for detail panels, side='left' for navigation",
      "Pass aria-labelledby to name the panel for screen readers",
      "The legacy Sheet/SheetContent layout wrappers are preserved for rétrocompatibilité",
    ],
  },
  // ── Professional SaaS Demo components ──────────────────────────────────────
  {
    id: "saas-kpi-grid",
    name: "SaasKpiGrid",
    importPath: "@/components/saas/saas-kpi-grid",
    category: "metric",
    domains: ["saas", "dashboard"],
    description: "8-metric KPI grid for SaaS dashboards: MRR, ARR, churn rate, activation, NPS, uptime, ARPU. Uses MetricCard with trend indicators.",
    useCases: ["SaaS main dashboard", "Executive overview"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Metrics are hardcoded to saas-demo-data constants"],
    tags: ["kpi", "metrics", "saas", "dashboard", "mrr", "churn"],
    recommendedProfiles: ["premium-saas", "minimal-dashboard"],
  },
  {
    id: "churn-risk-panel",
    name: "ChurnRiskPanel",
    importPath: "@/components/saas/churn-risk-panel",
    category: "card",
    domains: ["saas"],
    description: "Displays at-risk customers with churn score, signal description, and a contact CTA. Color-coded by risk level (high/medium/low).",
    useCases: ["SaaS dashboard churn section", "Customer success tooling"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["churn", "saas", "customer", "risk", "dashboard"],
    recommendedProfiles: ["premium-saas", "minimal-dashboard"],
  },
  {
    id: "onboarding-checklist",
    name: "OnboardingChecklist",
    importPath: "@/components/saas/onboarding-checklist",
    category: "card",
    domains: ["saas"],
    description: "Onboarding task list with progress bar. Checked tasks are struck through. Includes a CTA to continue setup when incomplete.",
    useCases: ["SaaS post-signup dashboard", "Guided setup flow"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["onboarding", "checklist", "setup", "saas"],
    recommendedProfiles: ["premium-saas", "minimal-dashboard"],
  },
  {
    id: "billing-summary-card",
    name: "BillingSummaryCard",
    importPath: "@/components/saas/billing-summary-card",
    category: "card",
    domains: ["saas"],
    description: "Compact billing summary: plan price, renewal date, payment method, and auto-renewal status in a single card.",
    useCases: ["Billing page header", "Dashboard subscription widget"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Status always shown as active in demo"],
    tags: ["billing", "subscription", "saas", "payment"],
    recommendedProfiles: ["premium-saas"],
  },
  {
    id: "usage-overview-panel",
    name: "UsageOverviewPanel",
    importPath: "@/components/saas/usage-overview-panel",
    category: "card",
    domains: ["saas"],
    description: "Full usage panel showing all quota items with accessible progress bars (role=progressbar, aria-label), warning/danger thresholds and inline alerts.",
    useCases: ["Usage page", "Billing sidebar"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Division-by-zero safe (limit > 0 guard)"],
    tags: ["usage", "quota", "metering", "saas", "accessibility"],
    recommendedProfiles: ["premium-saas", "minimal-dashboard"],
  },
  {
    id: "security-posture-card",
    name: "SecurityPostureCard",
    importPath: "@/components/saas/security-posture-card",
    category: "card",
    domains: ["saas"],
    description: "Security posture score (0-100) with color-coded progress bar and per-check icons (pass/warning/fail). Enterprise-ready audit surface.",
    useCases: ["Security page header", "Dashboard security widget"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["security", "compliance", "audit", "saas", "enterprise"],
    recommendedProfiles: ["premium-saas", "dark-technical"],
  },
  {
    id: "compliance-checklist",
    name: "ComplianceChecklist",
    importPath: "@/components/saas/compliance-checklist",
    category: "card",
    domains: ["saas"],
    description: "Compliance readiness checklist with pass/fail per item. Clearly marked as a preparation demo, not a real certification.",
    useCases: ["Security page", "Enterprise sales enablement"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Not a real compliance certification — demo only"],
    tags: ["compliance", "soc2", "gdpr", "security", "saas"],
    recommendedProfiles: ["premium-saas"],
  },

  // ── BOOKING (ZenSlot demo) ────────────────────────────────────────────────
  {
    id: "booking-kpi-grid",
    name: "BookingKpiGrid",
    importPath: "@/components/booking/booking-kpi-grid",
    category: "metric",
    domains: ["booking", "local-business"],
    description: "Grid of KPI cards for a booking admin dashboard: revenue, appointments, occupancy, no-shows, waitlist.",
    useCases: ["Booking admin dashboard", "Daily summary view"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["booking", "kpi", "dashboard", "metrics", "zenslot"],
    recommendedProfiles: ["warm-local"],
  },
  {
    id: "todays-appointments-list",
    name: "TodaysAppointmentsList",
    importPath: "@/components/booking/todays-appointments-list",
    category: "table",
    domains: ["booking", "local-business"],
    description: "Chronological list of today's appointments with staff, client, group attendance and status badges.",
    useCases: ["Booking dashboard agenda view", "Daily schedule overview"],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["booking", "appointments", "today", "schedule", "zenslot"],
    recommendedProfiles: ["warm-local"],
  },
  {
    id: "calendar-day-view",
    name: "CalendarDayView",
    importPath: "@/components/booking/calendar-day-view",
    category: "card",
    domains: ["booking", "local-business"],
    description: "Pixel-positioned day view calendar showing appointments as blocks on an hourly grid.",
    useCases: ["Booking calendar page", "Staff schedule view"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["CSS-based layout, no drag/drop"],
    tags: ["booking", "calendar", "day-view", "schedule", "zenslot"],
    recommendedProfiles: ["warm-local"],
  },
  {
    id: "service-management-table",
    name: "ServiceManagementTable",
    importPath: "@/components/booking/service-management-table",
    category: "table",
    domains: ["booking", "local-business"],
    description: "Table of bookable services with duration, price, deposit, buffer times, group/individual and active status.",
    useCases: ["Services admin page", "Service catalog management"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["booking", "services", "table", "admin", "zenslot"],
    recommendedProfiles: ["warm-local"],
  },
  {
    id: "client-directory-table",
    name: "ClientDirectoryTable",
    importPath: "@/components/booking/client-directory-table",
    category: "table",
    domains: ["booking", "local-business"],
    description: "CRM table of booking clients with segment badge, no-show count, LTV and upcoming appointment.",
    useCases: ["Booking CRM page", "Client management view"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: [],
    tags: ["booking", "clients", "crm", "table", "zenslot"],
    recommendedProfiles: ["warm-local"],
  },
  {
    id: "waitlist-panel",
    name: "WaitlistPanel",
    importPath: "@/components/booking/waitlist-panel",
    category: "card",
    domains: ["booking", "local-business"],
    description: "Ranked list of clients on a booking waitlist with notify-on-cancellation action.",
    useCases: ["Payments page", "Booking dashboard sidebar"],
    compatibleVariables: [],
    supportedStates: ["default", "empty"],
    maturity: "stable",
    limitations: [],
    tags: ["booking", "waitlist", "clients", "zenslot"],
    recommendedProfiles: ["warm-local"],
  },
  {
    id: "no-show-policy-card",
    name: "NoShowPolicyCard",
    importPath: "@/components/booking/no-show-policy-card",
    category: "card",
    domains: ["booking", "local-business"],
    description: "Displays cancellation/no-show policy rules and lists recent no-show incidents.",
    useCases: ["Payments page", "Policy settings display"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "stable",
    limitations: ["Demo mode — not wired to a real policy engine"],
    tags: ["booking", "no-show", "policy", "cancellation", "zenslot"],
    recommendedProfiles: ["warm-local"],
  },

  // ── 3D EXPERIENCE ───────────────────────────────────────────────────────────
  {
    id: "three-d-canvas",
    name: "ThreeDCanvas",
    importPath: "@/components/three-d/three-d-canvas",
    category: "media",
    domains: ["general", "ecommerce", "saas", "portfolio"],
    description: "SSR-safe entry point for any 3D scene: WebGL detection, error boundary, custom fallback, reducedMotionFallback and adaptive performance tiers.",
    useCases: [
      "Hero 3D decoratif derriere du contenu DOM",
      "Conteneur de toute scene R3F dans une page",
    ],
    compatibleVariables: [],
    supportedStates: ["default", "loading", "error"],
    maturity: "beta",
    limitations: [
      "Client component uniquement — ne jamais l'importer dans un server component sans island",
      "Le contenu SEO doit rester en DOM autour du canvas",
    ],
    tags: ["3d", "webgl", "canvas", "three", "r3f", "fallback"],
    visualWeight: "heavy",
    recommendedProfiles: ["dark-technical", "premium-saas", "creative-portfolio"],
    qualityLevels: ["premium"],
    requiredStates: ["default"],
    uxNotes: [
      "Performance: DPR plafonne par tier, antialias adaptatif, frameloop demand en reduced motion",
      "Accessibilite: role img + aria-label; fournir fallback et reducedMotionFallback complets",
      "Toujours prevoir un fallback DOM: la 3D est un decor, jamais un prerequis",
    ],
    examples: [
      {
        label: "Scene avec fallbacks",
        importStatement: 'import { ThreeDCanvas } from "@/components/three-d/three-d-canvas"',
        usage: '<ThreeDCanvas aria-label="Scene produit" fallback={<ThreeDFallback />} reducedMotionFallback={<ThreeDFallback />}><MyScene /></ThreeDCanvas>',
      },
    ],
  },
  {
    id: "orbit-product-viewer",
    name: "OrbitProductViewer",
    importPath: "@/components/three-d/orbit-product-viewer",
    category: "media",
    domains: ["ecommerce", "general"],
    description: "Product viewer preset: ThreeDCanvas plus stage lighting and bounded OrbitControls (clamped zoom and polar angle, no pan).",
    useCases: [
      "Showroom produit e-commerce",
      "Visualisation 360 d'un objet",
    ],
    compatibleVariables: [],
    supportedStates: ["default", "loading", "error"],
    maturity: "beta",
    limitations: ["Auto-rotation coupee sous prefers-reduced-motion"],
    tags: ["3d", "produit", "orbit", "viewer", "showroom"],
    visualWeight: "heavy",
    recommendedProfiles: ["commerce-clean", "dark-technical", "premium-saas"],
    qualityLevels: ["premium"],
    uxNotes: [
      "Performance: zoom borne min/maxDistance pour eviter le clipping et la desorientation",
      "Voir /demo/3d/product-showroom pour l'usage complet avec configurateur",
    ],
  },
  {
    id: "hotspot-marker",
    name: "HotspotMarker",
    importPath: "@/components/three-d/hotspot-marker",
    category: "media",
    domains: ["ecommerce", "general"],
    description: "In-scene hotspot rendered as a real DOM button via drei Html: keyboard-focusable and screen-reader accessible.",
    useCases: [
      "Points cles ancres sur un produit 3D",
      "Annotations de zones sur un modele",
    ],
    compatibleVariables: [],
    supportedStates: ["default", "selected"],
    maturity: "beta",
    limitations: [
      "Doit etre double d'une liste DOM hors canvas (ProductHotspotList) pour le fallback sans WebGL",
    ],
    tags: ["3d", "hotspot", "annotation", "accessibilite"],
    visualWeight: "light",
    recommendedProfiles: ["commerce-clean", "dark-technical"],
    qualityLevels: ["premium"],
    uxNotes: [
      "Accessibilite: vrai <button> avec aria-pressed et focus visible",
    ],
  },
  {
    id: "floating-card-scene",
    name: "FloatingCardScene",
    importPath: "@/components/three-d/floating-card-scene",
    category: "media",
    domains: ["saas", "portfolio", "general"],
    description: "Procedural floating dashboard panels with gentle bobbing and pointer parallax; zero asset downloads.",
    useCases: [
      "Hero SaaS avec cards en profondeur",
      "Backdrop de section features",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "beta",
    limitations: ["Decoratif: marquer le conteneur aria-hidden et garder le texte en DOM"],
    tags: ["3d", "saas", "cards", "flottant", "parallaxe"],
    visualWeight: "heavy",
    recommendedProfiles: ["premium-saas", "dark-technical"],
    qualityLevels: ["premium"],
    uxNotes: [
      "Performance: animation figee sous reduced motion, parallaxe adoucie sur mobile",
    ],
  },
  {
    id: "scroll-scene-section",
    name: "ScrollSceneSection",
    importPath: "@/components/three-d/scroll-scene-section",
    category: "layout",
    domains: ["general", "saas", "portfolio"],
    description: "Section wrapper exposing scroll progress (0..1) through context for scroll-driven 3D scenes, without scroll-jacking.",
    useCases: [
      "Hero 3D qui reagit au defilement",
      "Storytelling section par section",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "beta",
    limitations: ["Le progres est un ref: le lire dans useFrame, pas dans le rendu React"],
    tags: ["3d", "scroll", "storytelling", "section"],
    visualWeight: "light",
    recommendedProfiles: ["dark-technical", "creative-portfolio", "premium-saas"],
    qualityLevels: ["premium"],
    uxNotes: [
      "Performance: listener passif + rAF, aucune re-render React par tick de scroll",
      "Ne jamais bloquer ou detourner le defilement natif",
    ],
  },
  {
    id: "model-placeholder",
    name: "ModelPlaceholder",
    importPath: "@/components/three-d/model-placeholder",
    category: "media",
    domains: ["ecommerce", "general"],
    description: "Procedural premium product stand-in (device, box or orb) so demos ship without GLB downloads or licensing debt.",
    useCases: [
      "Produit fictif dans un showroom",
      "Placeholder en attendant un GLB licencie",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "beta",
    limitations: ["Formes generiques: pour un vrai produit client, prevoir un GLB licencie via le manifest"],
    tags: ["3d", "placeholder", "procedural", "produit"],
    visualWeight: "medium",
    recommendedProfiles: ["commerce-clean", "dark-technical"],
    qualityLevels: ["premium"],
    uxNotes: [
      "Voir lib/three-d/model-manifest.ts pour la politique GLB vs procedural",
    ],
  },
  {
    id: "three-d-fallback",
    name: "ThreeDFallback",
    importPath: "@/components/three-d/three-d-fallback",
    category: "media",
    domains: ["general", "ecommerce", "saas", "portfolio"],
    description: "Pure HTML/CSS stand-in for a 3D scene, used when WebGL is unavailable, on crash, or under reduced motion.",
    useCases: [
      "Fallback de ThreeDCanvas",
      "Apercu statique server-renderable",
    ],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "beta",
    limitations: [],
    tags: ["3d", "fallback", "statique", "accessibilite"],
    visualWeight: "medium",
    recommendedProfiles: ["dark-technical", "premium-saas", "commerce-clean"],
    qualityLevels: ["premium"],
    uxNotes: [
      "Accessibilite: role img avec label decrivant ce que la scene aurait montre",
    ],
  },
  {
    id: "performance-badge",
    name: "PerformanceBadge",
    importPath: "@/components/three-d/performance-badge",
    category: "badge",
    domains: ["general"],
    description: "DOM pill announcing the rendering tier the visitor gets (high quality, mobile-optimised, reduced motion or static).",
    useCases: ["Transparence du mode de rendu sur une page demo 3D"],
    compatibleVariables: [],
    supportedStates: ["default"],
    maturity: "beta",
    limitations: ["Pense pour les pages demo; optionnel sur un site client"],
    tags: ["3d", "performance", "badge", "transparence"],
    visualWeight: "light",
    recommendedProfiles: ["dark-technical"],
    qualityLevels: ["premium"],
  },
];
